#!/bin/bash
#
# wget -qO- https://github.com/escribano/hegel/raw/master/install | bash
#

export PHILOSOPHIE_PATH="$HOME/philosophie"
mkdir -p $PHILOSOPHIE_PATH
pushd $PHILOSOPHIE_PATH > /dev/null
git clone https://github.com/escribano/hegel.git
cd hegel
#install.hegel
hegel_config="config/hegelrc"
cp "${hegel_config}.template.sh" "${hegel_config}.sh"
#local count=0
#USER_PROFILE="$HOME/.profile"
#printf "\nsource $HEGEL_PATH/main.sh\n" >> $user_profile
printf "\nsource `pwd`/main.sh\n" >> $HOME/.profile
#printf "\nsource $HEGEL_PATH/main.sh\n"
#source ./main.sh
echo "--------------------"
echo "source `pwd`/main.sh"
echo "--------------------"
popd > /dev/null

#

# ec2
# ip
# r53
# sudo discoveryutil udnsflushcaches
# ksh.admin fichte
# wget -qO- https://github.com/escribano/hegel/raw/master/boot | bash
# logout
# ksh fichte
# wget -qO- https://github.com/escribano/hegel/raw/master/install | bash
# source /home/ademir/philosophie/hegel/main.sh
# nano .bashrc
# fixhostname fichte
# logout
# ksh fichte
# sudo nano /etc/hosts
# format.ssdb
# test.ssdb
# test.root
# config.swap
# free -h
# df -h

# sudo dpkg-reconfigure locales
# install.postgres
# config.pg.auth

# create.philo.db
# verify.philo.db

