#!/bin/bash
#
# wget -qO- https://github.com/escribano/hegel/raw/master/user | bash
#

sudo -i

sudo useradd -m ademir -s /bin/bash
#passwd ademir
#gedulah

sudo mkdir /home/ademir/.ssh
sudo wget -qO- https://github.com/escribano/hegel/raw/master/profile/id_rsa.pub \
  >> /home/ademir/.ssh/authorized_keys
sudo chmod 700 /home/ademir/.ssh
sudo chmod 600 /home/ademir/.ssh/authorized_keys
sudo chown -R ademir.ademir /home/ademir

#echo "ademir ALL=(ALL:ALL) ALL" > /etc/sudoers.d/master-user
sudo echo "ademir ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/master-user
sudo chmod 0440 /etc/sudoers.d/master-user
